language: node_js
node_js: --lts
before_script:
  - git config user.name "YOUR_NAME"
  - git config user.email "YOUR_EMAIL"
  - sed -i'' "s~https://github.com/iyonghua/blogs.git~https://${TravisToken}@github.com/iyonghua/blogs.git~" _config.yml
script:
  - hexo g
  - hexo d